version: "3.4"
services:
  front:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - 9000:9000
    networks:
      webnet:

networks:
  webnet: