version: "3.4"

services:
  user:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      webnet:
  proxy:
    build:
      context: ./server
      dockerfile: Dockerfile.Web
    ports:
      - 80:80
    networks:
      webnet:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      webnet:
volumes:
  mysqldata:
networks:
  webnet:
    external: true